/**************************************************************************************************************
 *
 * FILE NAME: main.c
 *
 * Description: main.c file for UART and PC communication protocol for controlling motors of a car
 *
 * Created on: August 26, 2023
 *
 * Author: Saeed Elsayed
 *
 **************************************************************************************************************/

#include <avr/io.h>
#include "uart.h"
#include "DC_motor.h"
#include "stepper_motor.h"
#include "lcd.h"
#include <avr/interrupt.h>


extern uint8 valid; // flag will take its value from uart.c file to know if the uart frame is right or not

extern uint8 duty_cycle;   // call the variable in the DC_motor.c file which
						   // carry the duty_cylcle wanted to be generated by the PWM


uint8 s1 =0;    // the first digit of seconds
uint8 s2 =0;    // the second digit of seconds
uint8 m1 =0;    // the first digit of minutes
uint8 m2 =0;    // the second digit of minutes
uint8 h1 =0;    // the first digit of hours
uint8 h2 =0;    // the second digit of hours

uint8 AM = 1; // to calculate the time is AM or PM

/*
 * Description:
 * function that initialize the PWM mode for timer0
 */
void PWM_Timer0_Start(uint8 duty_cycle){  /* send to it the duty cycle required */
	TCNT0 = 0;  // clear the counter register at the beginning
	OCR0 = duty_cycle;  // Setup the compare value based on the required input duty cycle

	// Setup the PWM mode with Non-Inverting
	// Setup the prescaler with F_CPU/8
	TCCR0 =  (1<<WGM00) | (1<<WGM01) | (1<<COM01) | (1<<CS01);

}


int main ()
{
	DcMotor_State  MotorDirection = STOP;    // initial state of the DC motor
	stepperMotor_direction stepperMotorDirection = STEPPER_STOP; // initial state of the stepper motor
	LCD_init();     // initialize the LCD
	DcMotor_Init(); // initialize the DC motor
	stepperMotor_Init();  // initialize the stepper motor
	uint8 recieved_frame[8]; // array to carry the received frame
	UART_init(9600);   // initialize the UART with baud rate 9600
	int speed = 0;    // variable to carry the speed from the frame
	uint8 angle = 0;  // variable to carry the motor angle from the frame
	LCD_displayStringRowColumn(0,0,"Spd: 0% Dirc: 0");   // initially display those two lines
	LCD_displayStringRowColumn(1,0,"TIME:00:00:00 AM");

	TCCR1A |= (1<<FOC1A) | (1<<FOC1B);
	TCCR1B |= (1<<CS10) | (1<<CS12) | (1<<WGM12);     //choosing the prescaler to be 1024    setting the compare mode
	TCNT1 =0;
	OCR1A = 1000;                  // compare will happen every 1s (1000 ms)
	TIMSK |=  (1<<OCIE1A);         // enable the interrupt for compare register A
	SREG |= (1<<7);                // enable the interrupt

	while(1)
	{
		UART_receiveString(recieved_frame);  // wait until the frame is received
		if (valid == 1)      // if the frame is right, start executing the process and if not, do nothing
		{
			int multiplication_factor = 1;   // factor to be multiplied by digits of speed and angle to calculate the speed and angle
			speed = 0;  //reset the value of the speed with each new frame
			angle = 0;  //reset the value of the angle with each new frame
			for(uint8 i = 2; i > 0; i--)
			{
				if(i > 0)  // this is because the angle just has 2 digits unlike the speed which has 3 digits
				{
					angle += (recieved_frame[i+3]-'0') * multiplication_factor;   // [i+3] because the angle digits in the frame is
				}                                                                 // after the speed digits by 3 places
				speed += (recieved_frame[i]-'0') *  multiplication_factor;  // because of that the frame is string, we should subtract
				multiplication_factor *= 10;                                // from the ASCII of zero then multiply by mul factor
			}

			if(recieved_frame[3] == 'F')   // check if the speed is forward
			{
				MotorDirection = ANTI_CLOCK_WISE;    // then make the motor move anti clock wise
			}
			else if(recieved_frame[3] == 'B')  // check if the speed is backward
			{
				MotorDirection = CLOCK_WISE;   // then make the motor move clock wise
			}

			if(recieved_frame[6] == 'R')       // check if the angle is to the right
			{
				stepperMotorDirection = STEPPER_CLOCK_WISE;   // then make the stepper motor move clock wise
			}
			else if (recieved_frame[6] == 'L') // check if the angle is to the lift
			{
				stepperMotorDirection = STEPPER_ANTI_CLOCK_WISE; // then make the stepper motor move anti clock wise
			}

		DcMotor_Rotate(MotorDirection, speed);  // send the direction to the motor and speed to calculate the duty cycle to be used by the timer
		PWM_Timer0_Start(duty_cycle); // give the duty cycle to the timer to generate the PWM signal
		stepperMotor_rotate(stepperMotorDirection, angle); // send the direction and required angle to the stepper motor
		LCD_moveCursor(0,4);   // move the cursor of the LCD to the place of the speed to adjust the speed
		if(speed < 10)     // check if the speed is only one digit then write empty space in the place of the second digit
			LCD_displayStringRowColumn(0,5," ");
		LCD_integerToString(speed);  // print the current speed on LCD
		if (recieved_frame[6] == 'L')  // check if the angle to left or right to write or remove the negative sign
			LCD_displayStringRowColumn(0,13,"-");
		else
			LCD_displayStringRowColumn(0,13," ");
		LCD_integerToString(angle);
		if(angle < 10)   // if the angle is only one digit then write empty space in the place of the second digit
			LCD_displayStringRowColumn(0,15," ");

		}
	}

	return 0;

}



ISR(TIMER1_COMPA_vect){ // changing the showed numbers every time an interrupt is executed
	if(s1 == 9){
		s1=0;
		LCD_moveCursor(1,12);
		LCD_integerToString(s1);
		if(s2 == 5){
			s2=0;
			LCD_moveCursor(1,11);
			LCD_integerToString(s2);
			if(m1 == 9){
				m1 = 0;
				LCD_moveCursor(1,9);
				LCD_integerToString(m1);
				if(m2 == 5){
					m2 =0;
					LCD_moveCursor(1,8);
					LCD_integerToString(m2);
					if(h1 == 1 || h1 == 2){  // check if the first digit of hours has reached 1 and in this case it will have to prospect
						if(h1 == 1 && h2 == 1) // either the second digit is 1 and in this case we will change the AM state
						{
							if(AM == 1)
								LCD_displayStringRowColumn(1,14,"PM"), AM = 0;
							else
								LCD_displayStringRowColumn(1,14,"AM");
							h1++;
						}
						if (h1 == 1 && h2 == 0) // or h2 is still zero and in this case we only increase h1
							h1++;
						if(h1 == 2)  // if h1 is actually 2 then we should make it 1
							h1 = 1;
						LCD_moveCursor(1,6);
						LCD_integerToString(h1);

						if(h2 == 1){
							h2 = 0;
							LCD_moveCursor(1,5);
							LCD_integerToString(h2);
						}
						else
						{
							h2++;
							LCD_moveCursor(1,5);
							LCD_integerToString(h2);
						}
					}
					else
					{
						h1++;
						LCD_moveCursor(1,6);
						LCD_integerToString(h1);
					}
				}
				else {
					m2++;
					LCD_moveCursor(1,8);
					LCD_integerToString(m2);
				}
			}
			else
			{
				m1++;
				LCD_moveCursor(1,9);
				LCD_integerToString(m1);
			}
		}
		else{
			s2++;
			LCD_moveCursor(1,11);
			LCD_integerToString(s2);
		}
	}
	else
	{
		s1++;
		LCD_moveCursor(1,12);
		LCD_integerToString(s1);
	}
}

